### ISSUE TITLE
Interpolated model vs. gridpoint

### ISSUE THREAD

**Issue by DanielAndreasen** [jobovy/apogee#15]
Hi Jo,

Did you try to create an interpolated model and compare to the grid point of the model atmospheres. E.g. create a model with `teff=5001`, `logg=4.01`, `metals=0.01` and compare this to the nearest grid point model?

Do you see any difference at this level?

Cheers,
Daniel

**Comment by jobovy** [comment]
Hi Daniel,

Yes, I've tried this and the differences are typically ~1 - 3 % in the atmospheric parameters (for your example the differences are:
 * ``rhox``: 1.7%
 * ``Teff``: 0.07%
 * ``P``: 1.6%
 * ``Ne``: 2.5%
 * ``kapp_ross``: 2.7%

I haven't tried how much of a difference this makes for synthetic spectra, but I would assume it's very small.

Are you using the code? The Kurucz atmospheres that I use are probably not that easy to find...

**Comment by DanielAndreasen** [comment]
I also don't know how much that affects the synthesis (I use the EW method). But it seems okay.

I write my own (with the collaborators) "wrapper" for MOOG, and we are inspired by this code for the model interpolation. Currently we have a Kurucz '95 grid, but we would like to update this for newer models, but also other models in the future.

**Comment by jobovy** [comment]
At least for APOGEE-like spectra it only changes the synthetic spectra by at most 0.003 (std. dev. 0.0006), so the impact is very small.

I'm just using linear interpolation, so the code should be easy to re-use for other model atmospheres. The actual implementation is very wrapped up with the structure of the APOGEE model-atmosphere library (http://iopscience.iop.org/1538-3881/144/4/120/pdf/aj_144_4_120.pdf), so might be difficult to use (although I think you can download the atmosphere grid here: http://www.iac.es/proyecto/ATLAS-APOGEE/).

**Comment by DanielAndreasen** [comment]
Thank you very much for the links :+1: I will test how much it affects the abundances later this week.
