### ISSUE TITLE
accessing apVisit spectra

### ISSUE THREAD

**Issue by mrawls** [jobovy/apogee#34]
Is it possible to use this package to download and inspect apVisit spectra (individual visits) in addition to apStar spectra (all visits added together)? It's not clear from the documentation, and this would be very useful!

**Comment by jobovy** [comment]
No, reading ``apVisit`` files is currently not supported, but note that the ``apStar`` files do contain the individual exposures as well. The difference is that in ``apStar`` the wavelength sampling is the standard APOGEE wavelength grid (equally spaced in log10(wavelength)), while in ``apVisit`` the spectra are on the native detector wavelength grid. You can read the individual spectra in apStar by reading HDU1 and selecting the columns 2 onwards (0 and 1 are the combined spectra).

**Comment by mrawls** [comment]
Awesome, thanks!

**Comment by mrawls** [comment]
Hi again :) I recently started using this approach to access individual visit data, and realized today that there is more than just a wavelength grid difference: the `apVisit` files are not RV-corrected while columns 2+ from the `apStar` HDU1 are. This is no good for science cases like mine (measuring precise RVs). Is there any possibility of supporting non-RV-subtracted `apVisit` data in the future?

**Comment by jobovy** [comment]
Yes, that's correct: ``apVisit`` files are on a different grid (non-RV corrected) from the ``apStar`` equivalent. I don't have any immediate plans for supporting ``apVisit`` files, but I would be happy with a pull request :smile: Should be easy to do based on the ``apStar`` routines.

**Comment by mrawls** [comment]
That's what I was afraid you would say! OK, we'll see... :smile:
