### ISSUE TITLE
numpy error lsf.py

### ISSUE THREAD

**Issue by jbirky** [jobovy/apogee#51]
Hi Jo, I noticed a bug in line 184 of lsf.py where the line `gd= True-numpy.isnan(pix)` returned the error

TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

I fixed this in my version of the code by changing the line to `gd= numpy.bitwise_xor(True, numpy.isnan(pix))`

**Comment by jobovy** [comment]
Thanks for reporting this. Yes, this is a known issue with the ``-`` operator being deprecated, but I hadn't fixed all instances yet. Should be fixed now.
