### ISSUE TITLE
Clarification turbospectrum abundances

### ISSUE THREAD

**Issue by drd13** [jobovy/apogee#56]
Hello,

I have been using your turbospectrum wrapper with atlas9 model atmospheres to generate synthetic spectra. After reading the documentation, I am still unsure how the elemental abundances are expressed. 

In the example 
```

import apogee.modelspec.turbospec
from apogee.modelatm import atlas9
atm= atlas9.Atlas9Atmosphere(teff=4750.,logg=2.5,metals=-0.25,am=0.25,cm=0.25)
# The following takes a while ...
synspec= apogee.modelspec.turbospec.synth([26,-0.25,0.25],[22,-0.3],modelatm=atm,\
         linelist='201404080919',lsf='all',cont='aspcap',vmacro=6.,isotopes='solar')

```
does [22,-0.3] refer to a [Ti/H] or  a [Ti/Fe] value?

Thank you for your help!

**Comment by jobovy** [comment]
The abundances specified in ``apogee.modelspec.turbospec.synth`` are differences with respect to the abundances in the model atmosphere (so they are neither [Ti/H] or [Ti/Fe]). So in this example, iron (26) is [-0.25,0.25] with respect to the ``metals=-0.25`` in the model atmosphere (so [Fe/H] = -0.5 and 0 in the end) and titanium (22) is -0.3 with respect to ``am=0.25`` (so [Ti/Fe] = -0.30 + 0.25 = -0.05). 

In general, alpha elements (8,10,12,14,16,18,20,22) are specified with respect to the ``am`` from the model atmosphere, carbon (6) with respect to ``cm``, and all other abundances are relative to ``metals``.

**Comment by jobovy** [comment]
Please let me know if this didn't resolve the issue or close the issue if it did. Thanks!

**Comment by drd13** [comment]
Sorry for that, your answer did indeed really clarified things. Thanks a lot for the quick response !
