### ISSUE TITLE
No default dr available for APOGEE_REDUX DR16, need to set it by hand

### ISSUE THREAD

**Issue by dutry** [jobovy/apogee#62]
When I try to `import apogee.tools.read as apread`, 
It shows the error:
`OSError: No default dr available for APOGEE_REDUX DR16, need to set it by hand`

Two environment variables have been set:
```
 'SDSS_LOCAL_SAS_MIRROR': '/Users/du/OneDrive/Work/gaia_lyrae_sample/apogee_jobovy/data',
 'RESULTS_VERS': 'l33'
```

The whole error screenshot:
<img width="1016" alt="Screen Shot 2020-12-23 at 11 51 14 AM" src="https://user-images.githubusercontent.com/17509207/102957408-4dfd2e80-4515-11eb-9eb2-193b12d6f4f0.png">

**Comment by jobovy** [comment]
That's weird! There must be something going wrong with the environment variable, because this should work with the current version I think. Could you try
```
import apogee.tools.path as appath
print(appath._APOGEE_REDUX,appath._DR16REDUX, appath._APOGEE_REDUX == appath._DR16REDUX)
```
and send the output?

**Comment by dutry** [comment]
<img width="1011" alt="Screen Shot 2020-12-28 at 5 00 41 PM" src="https://user-images.githubusercontent.com/17509207/103202767-43380480-492e-11eb-9029-54e0487f79f0.png">

**Comment by jobovy** [comment]
That's even weirder, because you don't seem to be able to load the `tools` submodule, which you seem to have been able to do before (when importing `apogee.tools.read`). Something may be corrupted about your installation, so the best thing to do might be to wipe the installation and freshly install the latest master branch.

**Comment by jobovy** [comment]
Did you install with `pip`? There is an `apogee` package on `pip` that's not the same!
